openapi: 3.0.0

info:
  title: Dynamic fields
  description: Create a form page with dynamic fields from database
  version: 1.0.0

servers:
- url: http://localhost:3000

paths:
  /api/form/{id}:
    get:
      summary: Returns a form by ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the form to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A form object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Form'
        default:
          description: Unexpected error

components:
  schemas:
    Table:
      type: object
      description: Informação da tabela dinâmica.
      properties:
        CodeIdentifier:
          type: string
          description: Código de identificação da tabela
        Description:
          type: string
          description: Descrição da tabela
        Name:
          type: string
          description: Nome da tabela
        Enabled:
          type: boolean
          description: Tabela habilitada
      required:
      - CodeIdentifier
      - Name
      - Enabled
    Column:
      type: object
      description: Informação da coluna da tabela dinâmica.
      properties:
        CodeIdentifier:
          type: string
          description: Código de identificação da coluna
        Description:
          type: string
          description: Descrição da coluna
        Table:
          $ref: '#/components/schemas/Table'
        Name:
          type: string
          description: Nome da coluna
        Enabled:
          type: boolean
          description: Coluna habilitada
      required:
      - CodeIdentifier
      - Table
      - Name
      - Enabled
    FieldValueType:
      type: object
      description: Tipo de valor para campo.
      properties:
        CodeIdentifier:
          type: string
          description: Código de identificação do tipo de valor
        Description:
          type: string
          description: Descrição do tipo de valor
        Enabled:
          type: boolean
          description: Tipo de valor habilitado
      required:
      - CodeIdentifier
      - Enabled
    Element:
      type: object
      description: Elemento que será renderizado no formulário.
      properties:
        CodeIdentifier:
          type: string
          description: Código de identificação do elemento
        Description:
          type: string
          description: Descrição do elemento
        FieldValueType:
          $ref: '#/components/schemas/FieldValueType'
        Enabled:
          type: boolean
          description: Elemento habilitado
      required:
      - CodeIdentifier
      - FieldValueType
      - Enabled
    ConditionType:
      type: object
      description: Tipo de condição antes de salvar. Tamanho min e max.
      properties:
        CodeIdentifier:
          type: string
          description: Código de identificação da condição
        Description:
          type: string
          description: Descrição da condição
        Enabled:
          type: boolean
          description: Condição habilitada
      required:
      - CodeIdentifier
      - Enabled
    UserType:
      type: object
      description: Tipo de usuário.
      properties:
        CodeIdentifier:
          type: string
          description: Código de identificação do tipo de usuário
        Description:
          type: string
          description: Descrição do tipo de usuário
        Enabled:
          type: boolean
          description: Tipo de usuário habilitado
      required:
      - CodeIdentifier
      - Enabled
    User:
      type: object
      description: Usuário.
      properties:
        CodeIdentifier:
          type: string
          description: Código de identificação de usuário
        UserType:
          $ref: '#/components/schemas/UserType'
        Name:
          type: string
          description: Nome do usuário
        Enabled:
          type: boolean
          description: Usuário habilitado
      required:
      - CodeIdentifier
      - UserType
      - Name
      - Enabled
    Field:
      type: object
      description: Informações para serem apresentadas no campo do formulário.
      properties:
        Description:
          type: string
          description: Descrição do campo
        Column:
          $ref: '#/components/schemas/Column'
        Name:
          type: string
          description: Nome do campo
        Caption:
          type: string
          description: Legenda do campo
        Hidden:
          type: boolean
          description: Campo oculto
        Conditions:
          type: array
          items:
            $ref: '#/components/schemas/FieldConditionUser'
        Enabled:
          type: boolean
          description: Campo habilitado
      required:
      - Column
      - Name
      - Caption
      - Hidden
      - Conditions
      - Enabled
    FieldConditionUser:
      type: object
      description: Lista de condições do campo para cada tipo de usuário.
      properties:
        UserType:
          $ref: '#/components/schemas/UserType'
        ConditionType:
          $ref: '#/components/schemas/ConditionType'
        Value:
          type: integer
          format: int32
          description: Valor de condição
        Enabled:
          type: boolean
          description: Condição do campo habilitada
      required:
      - UserType
      - ConditionType
      - Enabled
    Form:
      type: object
      description: Informações do formulário.
      properties:
        Description:
          type: string
          description: Descrição do formulário
        Fields:
          type: array
          items:
            $ref: '#/components/schemas/FormField'
        Enabled:
          type: boolean
          description: Formulário habilitado
      required:
      - Fields
      - Enabled
    FormField:
      type: object
      description: Lista de campos do formulário.
      properties:
        Field:
          $ref: '#/components/schemas/Field'
        Element:
          $ref: '#/components/schemas/Element'
        Name:
          type: string
          description: Nome do campo para o formulário
        Caption:
          type: string
          description: Legenda do campo para o formulário
        Hidden:
          type: boolean
          description: Campo para o formulário oculto
        RankOrder:
          type: integer
          format: int32
          description: Ordem de apresentação do campo
        Enabled:
          type: boolean
          description: Campo para o formulário oculto
      required:
      - Field
      - Element
      - Enabled
